### ISSUE TITLE
Line numbers on each line

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#164]
```
Very simple feature request. I would like to be able to have line numbers 
printed on each line, instead of just each fifth line.

Otherwise thanks for an awesome library!

- Egil
```

Original issue reported on code.google.com by `e...@assimilated.dk` on 28 Jul 2011 at 3:02

**Comment by amroamroamro** [comment]
This is now explained in the [faq](https://github.com/google/code-prettify#how-can-i-put-line-numbers-on-every-line-instead-of-just-every-fifth-line); first specify the `linenums` class, then style the appearance of a `<li>` elements to display numbers by setting `li.L0` to `li.L9`.

Here is an example: https://jsfiddle.net/amroamroamro/xurn5ksh/
