### ISSUE TITLE
Add support for Erlang

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#169]
```
I created a simple plugin to highlight Erlang code

Changes:
1) Attached lang-erlang.js (src/lang-erlang.js)
-- All following contained in diff.txt)
2) Update changelog for you (CHANGES.html)
3) Update documentation to include a link to where lang-erlang.js will reside 
post commit (README.html)
4) Update tests so that there is a test case for Erlang 
(tests/prettify_test.html)

This applies cleanly against HEAD in my repo
```

Original issue reported on code.google.com by `ache...@gmail.com` on 28 Aug 2011 at 12:08

Attachments:
* [lang-erlang.js](https://storage.googleapis.com/google-code-attachments/google-code-prettify/issue-169/comment-0/lang-erlang.js)
* [diff.txt](https://storage.googleapis.com/google-code-attachments/google-code-prettify/issue-169/comment-0/diff.txt)

**Comment by amroamroamro** [comment]
committed in 62d129a3
