### ISSUE TITLE
Capitalized C++ functions mistaken for types

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#202]
```
What steps will reproduce the problem?
1. Attached html, placed in tests/


What is the expected output?  What do you see instead?
Expected: The function AssignUInt64 is not colored as a type.
Actual: The function AssignUInt64 is colored as a type. 


What version are you using?  On what browser?
svn r220
18.0.1025.151


Please provide any additional information below.
It is possible that the only way to fix this is to not assume capitalized 
tokens are types (except under specific circumstances, such as, 
/class\s+(\w+)/). This appears to be the route github has chosen. 

For example:
https://github.com/joyent/node/blob/master/deps/v8/src/bignum.h.
https://github.com/joyent/node/blob/master/deps/v8/src/bignum.cc.
"class Bignum" is colored but no other references to the class are colored.

I know github is using pygments, not google-code-prettify, but I bring it up as 
a comparison.
```

Original issue reported on code.google.com by `matthew....@gmail.com` on 7 Apr 2012 at 11:51

Attachments:
* [type-function.html](https://storage.googleapis.com/google-code-attachments/google-code-prettify/issue-202/comment-0/type-function.html)

**Comment by amroamroamro** [comment]
Short of parsing the code, the next best thing was to follow the CamelCase [naming convention](https://en.wikipedia.org/wiki/Naming_convention_(programming)), where capitalized words usually denote class/type names.

This is not specific to C++, and applies to all languages in the core script [implemented](https://github.com/google/code-prettify/blob/master/js-modules/prettify.js#L630) with `sourceDecorator` function, specifically this rule:

    [PR_TYPE,        /^(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/, null],

It was discussed before, for example #70, #114
