### ISSUE TITLE
prettify dynamic generated content

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#268]
```
It seems this library is not able to prettify dynamic generated content. 
Related thread: 
https://groups.google.com/d/topic/js-code-prettifier/I7D0MKorRCQ/discussion

Please please fix this or document how it can be done. I think this is very 
important for a nice library/work like this. 
```

Original issue reported on code.google.com by `sebastigurin` on 2 Mar 2013 at 2:00

**Comment by amroamroamro** [comment]
You can use the `PR.prettyPrintOne` function; it takes HTML text as input (what you would normally place inside a PRE tag) and it returns that text prettified.

This is different from the regular `PR.prettyPrint` function which works on DOM elements; it finds all PRE tags in the page with the `prettyprint` class and prettifies them.

Here are some examples I posted on other issues using `prettyPrintOne`:
- https://jsfiddle.net/amroamroamro/d3xc4nne/1/
- https://jsfiddle.net/amroamroamro/c64atxbu/
- https://jsfiddle.net/amroamroamro/pch5hwd1/
