### ISSUE TITLE
// is handled as line comment in ML

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#322]
```
What steps will reproduce the problem?

Any ML source code containing `//`.

What is the expected output?  What do you see instead?

`//` should be a normal operator (like `+`) but is printed as if it was a line 
comment. Typical members of the ML family, like Standard ML, OCaml, ..., do not 
have line comments, they only have block comments with `(*` and `*)`.


```

Original issue reported on code.google.com by `c.sterna...@gmail.com` on 17 Dec 2013 at 12:36

**Comment by amroamroamro** [comment]
According to [this](http://dungpa.github.io/fsharp-cheatsheet/), F# (an ML dialect also covered by [`lang-ml.js`](https://github.com/google/code-prettify/blob/master/src/lang-ml.js)) supports both block comments and "end-of-line comments":

``` fs
(* This is block comment *)

// And this is line comment
```
