### ISSUE TITLE
XML attributes with < symbol in value breaks syntax highlighting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#339]
```
What steps will reproduce the problem?
1. Set language to XML
2. Use attribute value with greater than or less than symbol
2. Syntax highlighting will break

Here's an example of a code snippet which breaks prettify.  

<pre class='prettyprint xml'><code>
    &lt;Person AgeCategory="&lt;3" &gt;&lt;/Person&gt;
</code></pre>

Here's a fiddle with the same code:
http://jsfiddle.net/KyleMit/qpEhr/

What is the expected output?  What do you see instead?
Here's a screenshot of the current output vs. my expected output:
http://i.imgur.com/016JEsw.png

What version are you using?  On what browser?
https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js
Running in Chrome (same for all browsers)

Please provide any additional information below.
Since the < or > symbol exists inside of quotes, it should be treated as a 
string and should not affect the way that the code sample is parsed.

This is particularly an issue when attempting to use ASP.NET code (which 
usually passes as XML) because of the use of inline script tags. 
Here's an asp.net example:
http://jsfiddle.net/KyleMit/qpEhr/0/
http://i.imgur.com/wiuQDoK.png
```

Original issue reported on code.google.com by `Kyle...@gmail.com` on 2 Apr 2014 at 7:47

**Comment by amroamroamro** [comment]
I think there is some confusion here..

Let say you want to end up with this XML document:
```
<?xml version="1.0"?>
<Person AgeCategory="<3" ></Person>
```

On one hand, if you want valid XML, you must escape special characters inside attribute values (i.e `<3` inside the attribute value becomes `&lt;3`). So the file would contain this:
``` xml
<Person AgeCategory="&lt;3" ></Person>
```

*You can verify this fact using [W3C Markup Validation Service](https://validator.w3.org/#validate_by_input).*

On the other hand, if you want to include the above code inside `<pre>` , you must in turn escape those special characters (`<` turns to `&lt;`, `>` into `&gt;`, and `&` into `&amp;`), meaning you have to use
``` html
<pre>
&lt;Person AgeCategory="&amp;lt;3" &gt;&lt;/Person&gt;
</pre>
```

So there is really escaping on two levels here!

---

Here is a live demo showing the correct way of writing this:
https://jsfiddle.net/amroamroamro/fqbxur91/1/
