### ISSUE TITLE
How to use syntax highlighting in asp.net

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#343]
```
How to use syntax highlighting in asp.net


```

Original issue reported on code.google.com by `geniuspu...@gmail.com` on 22 May 2014 at 6:34

**Comment by amroamroamro** [comment]
The default language handler (HTML/XML) can handle ASP.NET syntax.
Here is an example: https://jsfiddle.net/amroamroamro/8rtkdthu/
