### ISSUE TITLE
Indentation on css

### ISSUE THREAD

**Issue by nicolasroux** [google/code-prettify#378]
When I use pretty-print on css, I usually add some lines like this:

<pre class="code prettyprint lang-css">
body
{
padding-top: 50px;
}
</pre>

I am expecting that prettyprinted code should indent the line padding-top.
But it is not the case :
![prettyprint](https://cloud.githubusercontent.com/assets/7628019/8473034/922e808e-20a6-11e5-91bc-e5441b0be053.png) 
Is it something wrong or do I miss something ?

**Comment by amroamroamro** [comment]
code-prettify does not re-indent your code (think how you would do that for languages like Python!), it will only style your source code (basically a syntax highlighter)...

**Comment by nicolasroux** [comment]
ok, thanks.
