### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by k-lange** [google/code-prettify#379]
It would be nice being able to install this via npm, but the missing package.json prevents that at the moment. Can you please add one? Thanks :)

**Comment by graingert** [comment]
@mikesamuel any update on this?

**Comment by amroamroamro** [comment]
related #389

**Comment by amroamroamro** [comment]
I think it makes more sense to create a Bower package than an NPM package.

code-prettify does not export a "module" in the node.js sense.
It's meant as a front-end library, by loading it as a regular <script> in your HTML page, and Bower fits better for frontend dependencies.

**Comment by graingert** [comment]
This isn't an issue. Just use AMD and then packagers like webpack and
browserify can use the package from npm. Yeah they support bower with extra
configuration... But nobody likes bower anymore.

**Comment by graingert** [comment]
Not exporting a module isn't an issue, however simply being on npm allows frontend packagers like webpack and browserify to use the package.

Yeah they support bower with extra configuration... But nobody likes extra configuration or bower.

**Comment by graingert** [comment]
@amroamroamro it would be great to export an AMD module for easier use.

**Comment by amroamroamro** [comment]
@graingert 
checking the code it actually defines an AMD module there at the end:
https://github.com/google/code-prettify/blob/master/src/prettify.js#L1722

Is that enough for it to be consumed by module loaders and bundlers?


*PS: I'm not a developer of prettify, I just help maintain a language extension I contributed.*

**Comment by graingert** [comment]
@amroamroamro looks good. Could do with using UMD.

**Comment by amroamroamro** [comment]
@graingert 
So we just need to add a `package.json` or a `bower.json` config file, and then to publish it on the selected package registry, right?

We'll have to ask @mikesamuel for this part though.

**Comment by amroamroamro** [comment]
@graingert 
By the way, to get an idea I was looking at how the [jquery NPM package](https://www.npmjs.com/package/jquery) is configured (since it similarly needs a `window` object to work). It uses the following pattern:

``` js
(function(global, factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        module.exports = global.document ?
            factory(global, true) :
            function(w) {
                if (!w.document) {
                    throw new Error("jQuery requires a window with a document");
                }
                return factory(w);
            };
    } else {
        factory(global);
    }
}( typeof window !== "undefined" ? window : this, function( window, noGlobal ) {
    var jQuery = ...;  // the whole implementation

    if (!noGlobal) {
        window.jQuery = window.$ = jQuery;
    }
    return jQuery;
}));
```

That's supposed to work for browsers, Browserify/Webpack, and node.js.
When included as a `<script>` tag in a page, it runs as usual and sets `window.jQuery` globally. When used in an environment like Node.js, it exports a factory function, which later receives a mocked `window` object (e.g from `jsdom`): `var $ = require('jquery')(window);`

**Comment by graingert** [comment]
prettyify probably doesn't need window for it's core operations.

**Comment by amroamroamro** [comment]
AFAIK it does, it creates DOM elements in the core function

**Comment by graingert** [comment]
@amroamroamro bah and the whole thing requires a global "PR" object.

**Comment by graingert** [comment]
@amroamroamro well it could use jsdom....

**Comment by mikesamuel** [comment]
IIRC it gets the document to create elements by looking at the
ownerDocument of the containing element and the global PR object is not
exported by run_prettify

**Comment by amroamroamro** [comment]
added `package.json` in #469

**Comment by alex-milanov** [comment]
#476 I've created a pull request with small changes so that it can be used inside of a npm based pipeline
