### ISSUE TITLE
Add support for Swift language

### ISSUE THREAD

**Issue by guyvo** [google/code-prettify#380]
As Swift is announced to be open sourced by Apple later this year I think it would be nice to have an extension ready for this language. Perhaps starting from lang-c or basic and extend with things like optionals ? ! , new keywords like defer , mutate , parameters inout ,...

Thanks
Guy

**Comment by morajabi** [comment]
like

**Comment by mikesamuel** [comment]
You can thank chrisrecher who wrote [`lang-swift.js`](https://github.com/google/code-prettify/commits/master/src/lang-swift.js)
