### ISSUE TITLE
source missing license header

### ISSUE THREAD

**Issue by KelseyBlodgett** [google/code-prettify#382]
I noticed that the JavaScript file doesn't have a license header. This seems to be a common practice amongst JavaScript libraries.
Would it be possible to add the information to the file so users can easily adhere to the project's license?
Something like:
Licensed under the Apache 2.0 License

**Comment by mikesamuel** [comment]
Which file is missing a license header?

**Comment by amroamroamro** [comment]
probably fixed in PR #391
