### ISSUE TITLE
Avast complains about HTML:Script-inf

### ISSUE THREAD

**Issue by kbilsted** [google/code-prettify#390]
As of today when visiting a site using the prettifyer i get a warning from AVAST anti virus that is has blocked access to a dangerous site. Eg. i cannot visit https://rawgit.com/google/code-prettify/master/examples/quine.html  which is linked from the front page

**Comment by mikesamuel** [comment]
Does this happen for all rawgit pages or this page in particular?

I sent a report via Avast's contact site but I have no idea whether that's a black hole or not.

**Comment by kbilsted** [comment]
I think it was multiple pages. 

I've also sent a few requests for whitelisting from within the Avast application. I haven't heard back from them, but I think around Tuesday it was working fine again with no warnings.
