### ISSUE TITLE
SQL keywords unrecognized when in uppercase

### ISSUE THREAD

**Issue by Worst45** [google/code-prettify#397]
Hello, I tried the following code:
```html
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
<pre class="prettyprint lang-sql">
    SELECT A.column1 AS "Col1", ColTwo from table AS A WHERE MyId LIKE "test"
</pre>
```

* `from` is recognized as a keyword (`kwd` class)
* other keywords (`select` and `WHERE`) are identified as plain text (`pln`)

Is there a way to tell code-prettify to match even uppercase words?

Thanks a lot.

**Comment by mikesamuel** [comment]
I think you need to load the SQL module thus `https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?lang=sql`

See the [auto-loader docs](https://github.com/google/code-prettify/blob/master/docs/getting_started.md#auto-loader) for more detail.
