### ISSUE TITLE
prettyPrint function not defined

### ISSUE THREAD

**Issue by skywebdeveloper** [google/code-prettify#398]
as mentioned in faq 
to use this
addEventListener('load', prettyPrint, false);

it gives me error that prettyPrint function is not defined

**Comment by mikesamuel** [comment]
If you can supply more detail about your setup then I can try and figure out what's going wrong.

**Comment by skywebdeveloper** [comment]
i am using cdn mentioned in faq. The script load and renders code perfectly. But i am modifying code with javascript later and then i want to highlight my code syntax again for that i am calling prettyPrint fucnction.

Which function is used to highlight codes?

**Comment by mikesamuel** [comment]
An HTML snippet that reproduces the problem would help me answer your question.

**Comment by skywebdeveloper** [comment]
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
<textarea id="question_content" onKeyUp="render();"></textarea>
<code class="prettyprint"><div id="preview">Here is some deafult codes</div></code>
<script>
function render(){//
	var question_content = $("question_content").value;
	//Sanitizing data//
	var entitles = {//List of all Html entitles & custum entitles
		'<':"&lt;",
		'>':"&gt;",
		'\n':"<br>",
		'[b]':"<b>",
		'[/b]':"</b>",
		'[i]':"<i>",	
		'[/i]':"</i>",
		'[code]':"<code class='prettyprint'>",
		'[/code]':"</code>",
		'[link]':"<a href="+href+">",
		'[link]':"</a>"
		
	}
	question_content = question_content.replace(/<|>|\n|\[b]|\[\/b]|\[i]|\[\/i]|\[code]|\[\/code]|\[link]|\[\/link]/gi, function (html_ent){return entitles[html_ent];});
	//question_content = question_content.replace(/'/, "</b>");
	var preview = $("preview");
	preview.innerHTML = question_content;	
	//prettyPrint();
}
</script>

**Comment by skywebdeveloper** [comment]
```
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
<textarea id="question_content" onKeyUp="render();"></textarea>
<code class="prettyprint"><div id="preview">Here is some deafult codes</div></code>
<script>
function render(){//
	var question_content = $("question_content").value;
	//Sanitizing data//
	var entitles = {//List of all Html entitles & custum entitles
		'<':"&lt;",
		'>':"&gt;",
		'\n':"<br>",
		'[b]':"<b>",
		'[/b]':"</b>",
		'[i]':"<i>",	
		'[/i]':"</i>",
		'[code]':"<code class='prettyprint'>",
		'[/code]':"</code>",
		'[link]':"<a href="+href+">",
		'[link]':"</a>"
		
	}
	question_content = question_content.replace(/<|>|\n|\[b]|\[\/b]|\[i]|\[\/i]|\[code]|\[\/code]|\[link]|\[\/link]/gi, function (html_ent){return entitles[html_ent];});
	//question_content = question_content.replace(/'/, "</b>");
	var preview = $("preview");
	preview.innerHTML = question_content;	
	//prettyPrint();
}
</script>
```

**Comment by mikesamuel** [comment]
Since you're using run_prettify.js instead of loading prettify.js, you should use `PR.prettyPrint`.  The original script added too many names to the global scope, so I established the `PR` namespace and when I wrote the auto-loader I had no need to be backwards compatible with my earlier bad behavior.

I'll update the FAQ to mention PR.

**Comment by skywebdeveloper** [comment]
now it doesn't give any errors but its not highlighting syntax.

**Comment by mikesamuel** [comment]
Do you see anything in the dev console?

**Comment by skywebdeveloper** [comment]
Nope

**Comment by mikesamuel** [comment]
It looks like you want to load prettify.js instead of run_prettify.js and then the function that prettyprints code is [`PR.prettyPrintOne`](https://github.com/google/code-prettify/blob/master/src/prettify.js#L144-L153).

**Comment by amroamroamro** [comment]
for posterity's sake, here is an that does syntax highlighting as you type code: https://jsfiddle.net/amroamroamro/c64atxbu/
