### ISSUE TITLE
JSON support?

### ISSUE THREAD

**Issue by bgSosh** [google/code-prettify#399]
JSON seems to get output on one long line.  Is JSON data formatting not supported?

**Comment by mikesamuel** [comment]
This project does syntax highlighting, not reformatting of source code.

**Comment by bgSosh** [comment]
Well that's a pity.  Pretty printing JSON usually involves printing elements on different lines (pretty useless otherwise).

**Comment by mikesamuel** [comment]
If you want to pretty print JSON in javascript try

```js
JSON.stringify(JSON.parse(myJSON))
```

**Comment by bgSosh** [comment]
Thanks, I'll give that a try.

**Comment by bigomega** [comment]
Try something like
```javascript
JSON.stringify(JSON.parse(myJSON),null, "\t");
/*
{
	"a": 3,
	"b": [
		{
			"a": 33
		}
	]
}
*/
```
