### ISSUE TITLE
Wrapping long lines of code

### ISSUE THREAD

**Issue by johnnyreilly** [google/code-prettify#429]
Heya,

Thanks for the work on code-prettify!  Is there a way to instruct that long lines of code should be wrapped?

In [this long line example](http://blog.johnnyreilly.com/2016/03/tfs-2012-meet-powershell-karma-and-buildnumber.html) you can see it does not...  

![image](https://cloud.githubusercontent.com/assets/1010525/14380150/f6eaca4e-fd75-11e5-9c9a-d43c34a3b423.png)

**Comment by epicgirl1998** [comment]
you can do that using css

```css
pre.prettyprint {
	white-space: pre-wrap;
}
```
![image](https://cloud.githubusercontent.com/assets/18232081/14414272/24dae77a-ff99-11e5-96ff-56934e76b688.png)

**Comment by johnnyreilly** [comment]
Works a treat; thanks!
