### ISSUE TITLE
Prettifying JSON Schema

### ISSUE THREAD

**Issue by halindrome** [google/code-prettify#434]
JSON Schema notation [1] is often used to specify validation restrictions on JSON.  I don't think the current tool supports / has arcane knowledge of the terms that JSON Schema uses and does anything special with them.  Am I right?  Assuming I am, can anyone give me a hint where to start trying to define an extension that would support it?

[1] http://json-schema.org/documentation.html

**Comment by amroamroamro** [comment]
It does work with the existing JSON handler (`lang-json`). Here is an example https://jsfiddle.net/amroamroamro/swybxhmw/

Of course stuff like `{"key": "value"}` are treated as regular strings, no attempt at detecting special key names.

if you want to write a new language handler specifically for JSON Schema, you can start by seeing an example of included extensions `lang-*.js`: https://github.com/google/code-prettify/tree/master/src

**Comment by halindrome** [comment]
Thanks.  As it turns out, the tool that was relying upon this transitioned to using highlight.js recently, so this is less urgent for us.  However, we are planning on doing a json-ld and json-schema module for highlight, so we will try to feed one into your project too.
