### ISSUE TITLE
Adding content after the page is loaded (and was pretty-printed)

### ISSUE THREAD

**Issue by Pumpapa** [google/code-prettify#444]
I'm adding code snippets after the page has loaded. They aren't pretty-printed.
In some documentation the function prettyPrint is mentioned, but this just results in "Uncaught ReferenceError: prettyPrint is not defined"

What is the recommended way to do this?

**Comment by amroamroamro** [comment]
use the ` prettyPrintOne` function. Here is an example I previously posted: https://jsfiddle.net/amroamroamro/d3xc4nne/1/

**Comment by Pumpapa** [comment]
Sadly, 'Uncaught ReferenceError: prettyPrintOne is not defined'
I'm dynamically adding code-prettify.
Before I add it a <pre ...> is just plain 
After I add it that <pre ...> is highlighted
But when I add further <pre>'s they aren't

So code-prettify is loaded; I can see it in the debugger, but I can't call prettyPrintOne

**Comment by amroamroamro** [comment]
how are you loading code-prettify? have you tried `PR.prettyPrintOne`? a small reproducible example would help..

Also note how the `prettyPrintOne` function is called; it takes a chunk of text as input and it returns that text prettified. This is different from the regular `prettyPrint` function which works on DOM elements (by finding `<pre>` and `<code>` tags with the `prettyprint` class).

**Comment by Pumpapa** [comment]
Great! The PR. did it.
Normaly I would include a reproducible example, but it's kind of a mess right now.

Thanks very much for your help!

**Comment by lstandish** [comment]
> use the `prettyPrintOne` function. Here is an example I previously posted: https://jsfiddle.net/amroamroamro/d3xc4nne/1/

Thanks amroamroamro, your post helped me.

**Comment by KissBalazs** [comment]
Is there any way, to import this `PR.prettyPrintOne` function into TypeScript projects nicely? 
I can call it after the lib is loaded, but I cannot import it (`import * as CodePrettify from 'node_modules/code-prettify/src/run_prettify.js';`) as it is described in an antonym function, injected into global namespace I think?
