### ISSUE TITLE
Functionality request - Code formatting

### ISSUE THREAD

**Issue by matjazmav** [google/code-prettify#450]
Hello, I have request about new functionality. Since this is tool is meant to prettify code it would be cool that you can format code before you highlight is.

From:
```js
function fun() { console.log('...'); }
```

To:
```js
function fun() {
    console.log('...');
}
```

Or is there any other tool that support this (multipla languages)?
Thanks!

**Comment by Q8Xbox** [comment]
Yes, This will help a lot :+1:

**Comment by amroamroamro** [comment]
Sorry but this is unlikely to be implemented in code-prettify. After all it is a syntax highlighter, not a code beautifier...

You might wanna look into other projects like [astyle](http://astyle.sourceforge.net/) or [uncrustify](http://uncrustify.sourceforge.net/) which work on multiple languages, or language-specific ones (too many to list).
