### ISSUE TITLE
Add main fileld to package.json

### ISSUE THREAD

**Issue by aSegatto** [google/code-prettify#462]
Is it possible to add "main" field to package.json configuration file ? We are currently setting it to "bin/prettify.min.js" after npm update . This is necessary in order to use this library with angular-cli. 
If approved, I can provide a pull request.

**Comment by aSegatto** [comment]
I've just noticed that npm support is not in the github repo . If it's like that, please ignore this issue ...

**Comment by amroamroamro** [comment]
depends on #379

**Comment by amroamroamro** [comment]
added `package.json` in #469.
