### ISSUE TITLE
404 when I try to download the resources

### ISSUE THREAD

**Issue by henrywright** [google/code-prettify#481]
The link in the [Getting Started](https://github.com/google/code-prettify/blob/master/docs/getting_started.md) page is returning a 404

https://raw.githubusercontent.com/google/code-prettify/master/distrib/prettify-small.tgz

**Comment by alex-milanov** [comment]
#479

**Comment by henrywright** [comment]
There seems to be a .zip available here

https://github.com/google/code-prettify/blob/master/distrib/prettify-small.zip

**Comment by amroamroamro** [comment]
yep, forgot to update the docs. ZIP file is still provided.
Closing as duplicate of #479.
