### ISSUE TITLE
Syntax highlighting for python 3 treats `//` as comment

### ISSUE THREAD

**Issue by embg** [google/code-prettify#482]
In a [stack exchange question](https://codereview.stackexchange.com/questions/159186/counting-increasing-subsequences-with-a-hackers-binary-index-tree-can-it-b), I wrote code including the line

````
sum(f[(s // nn)*nn : s])
````
This should all be the same color, since `//` means integer division in python 3. However, everything including and after the `//` was colored grey (as opposed to black), as if the text were commented. Is it possible to fix this? Based on how I tagged my question, the argument `lang-py` should have been passed to code-prettify.

**Comment by kevin-brown** [comment]
I cannot reproduce this issue on that Stack Exchange question.

![image](https://cloud.githubusercontent.com/assets/1991850/24439025/9ac0cb72-1419-11e7-8f4f-24013525491f.png)

And looking at the generated code, it's detecting the `//` as a symbol instead of a comment.

**Comment by embg** [comment]
Oh, gosh, now that I go to the link it works. I think maybe when I first wrote the question it wasn't tagged yet or something... Sorry!

**Comment by embg** [comment]
Edit: I figured out what happened. This is a stack exchange issue, not a code-prettify issue. 

I tagged my question `python-3.x`. With only that tag, the highlighting is wrong; it must not be passing `lang-py`. A mod tagged my question `python`, which must have added the `lang-py` argument. I will post this on stack exchange meta.

**Comment by amroamroamro** [comment]
SE determines the language used for highlighting based on question tags. You can also specify an explicit language hint. You can read more about it in this FAQ: [What is syntax highlighting and how does it work?](https://meta.stackexchange.com/questions/184108/what-is-syntax-highlighting-and-how-does-it-work).it 

Note that the default language handler is a generic one that works on most C-like languages, and it treats `//` as a line comment.
