### ISSUE TITLE
lang-html does not support data attributes

### ISSUE THREAD

**Issue by benpetersen** [google/code-prettify#494]
The following code prints out "Text" rather than the entire HTML

`<pre class="prettyprint lang-html">
    <data name="Data.Text" xml:space="preserve">
        <value>Text</value>
    </data>
</pre>`

**Comment by kevin-brown** [comment]
Are you sure it's not just an issue with you using the raw HTML instead of escaping it within the `<pre>`?

I wasn't able to reproduce this issue using an older version of prettify at http://coderazzi.net/javascript/prettify/index.html

**Comment by amroamroamro** [comment]
@benpetersen 
You have to escape special characters `<`, `>`, and `&` inside the PRE tag:

> https://jsfiddle.net/amroamroamro/0fd7y0vm/

This is really an HTML thing, otherwise the browser interprets them as tags before code-prettify even runs.
