### ISSUE TITLE
404 on CDN

### ISSUE THREAD

**Issue by bencmbrook** [google/code-prettify#501]
https://cdn.rawgit.com/google/code-prettify/master/loader/lang-json.js

Is unavailable. Is there an updated link?

**Comment by amroamroamro** [comment]
There is no separate extension for `lang-json.js`.
JSON support is included in the core `prettify.js`, just specify the `lang-json` class.

Here is a live example: https://jsfiddle.net/amroamroamro/swybxhmw/
