### ISSUE TITLE
can i highlight a specific line?

### ISSUE THREAD

**Issue by divinity76** [google/code-prettify#514]
Edit: nvm, figured it out: `document.querySelector("pre ol li:nth-child(448)").style["background-color"]="red";`

for example, i'd like to make the background color of line 448 red (because there's something wrong with it), any idea how i can do that?

**Comment by divinity76** [comment]
figured it out, see above

**Comment by amroamroamro** [comment]
yep, here is an example I previously posted:
https://github.com/google/code-prettify/issues/136#issuecomment-232508196
