### ISSUE TITLE
How to remove black box around code (or change it's color)

### ISSUE THREAD

**Issue by robertdknight** [google/code-prettify#517]
This software works great. The code highlighting places a black box around the code.  How can I remove or change the color of this box? [Example](https://rdknight.org/blog/software/sha1-hash-in-right-click-menu)

**Comment by amroamroamro** [comment]
Use CSS to set border=0 on `pre.prettyprint` elements.

This comes from the default stylesheet `prettify.css` which adds the border:
https://github.com/google/code-prettify/blob/master/src/prettify.css

**Comment by robertdknight** [comment]
Thanks!  Problem solved.
