### ISSUE TITLE
Support question: formatting js code 

### ISSUE THREAD

**Issue by ORESoftware** [google/code-prettify#521]
I have the following html:

```html
 <div>
    <pre class="prettyprint"><code class="language-js">{{muchoCodo}}</code></pre>
  </div>
```

I get this output:

<img width="350" alt="screenshot 2018-01-05 23 01 36" src="https://user-images.githubusercontent.com/11139560/34637474-7701b5ac-f26c-11e7-80fc-efb343e5a004.png">

I was hoping that there would be some syntax highlighting - highlighting javascript keywords etc. But it's just black/white text with a certain font. Am I doing something wrong?

**Comment by ORESoftware** [comment]
I also tried this, same result:

```html
<pre class="prettyprint lang-js">{{muchoCodo}}</pre>
```

**Comment by ORESoftware** [comment]
Nvm, the script didn't actually load:

`Refused to load the script 'https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'".`

if you know anything about getting chrome extensions to load "unsafe" code please help

**Comment by amroamroamro** [comment]
I don't know about chrome extensions, but maybe you can directly bundle `prettify.js` and `prettify.css` with the extension, rather than loading them externally.

**Comment by ORESoftware** [comment]
yeah, that's what I had to do, that seemed to work. Thanks.
