### ISSUE TITLE
Python highlighting combination """" " """"

### ISSUE THREAD

**Issue by giacomomarchioro** [google/code-prettify#541]
Dear all, 
I could find this issue.
I have experienced some problem with Python highlighting:

```python
 with open(output,'a') as f:
                f.write(r"""<path d=" """)
                f.write("M %s %s" %(xstartpoint,ystartpoint))
                f.write("A %s %s 0 %s 0 %s %s" 
                        %(r,r,large_arc_flag,xendpoint,yendpoint))
                f.write("L %s %s" %(xcenter,ycenter))
                f.write(r"""Z"/>""" )
```

This code is highlighted badly because of the combination """<path d=" """.

You can see the result [here](https://stackoverflow.com/a/50159157/2132157).

Thanks best regards, 
GM

**Comment by mikesamuel** [comment]
I added a language hint ([revision](https://stackoverflow.com/posts/50159157/revisions)) `<!-- language: lang-py -->` before that code block and now it prettifies properly.
