### ISSUE TITLE
Code-prettify treats the character literal '"' as the start of a double quoted string

### ISSUE THREAD

**Issue by mspertus** [google/code-prettify#561]
For example, the following snippet from the C++ standard renders as a string starting at the " below

```
template&lt;class charT&gt;
T11 quoted(const charT* s, charT delim = charT(’"’), charT escape = charT(’\\’));
  // Just green from here on                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^           
```

**Comment by amroamroamro** [comment]
You're using the wrong [single-quote character](https://en.wikipedia.org/wiki/Apostrophe#Computing), i.e `’` ([U+2019](https://www.fileformat.info/info/unicode/char/2019/index.htm)) vs. `'` ([U+0027](https://www.fileformat.info/info/unicode/char/0027/index.htm)).

I'm guessing you copied the snippet from a blog or a word document (which tend to insert these so called "smart quotes")..

**Comment by mspertus** [comment]
Arggh, that is correct! Interestingly, that would have been the first thing I thought of had I pasted it from a web page, but I actually copied it from the C++ Standard PDF itself. Sorry for wasting your time. I may switch this to being an issue with the standard...
