### ISSUE TITLE
"code prettifier" doesn't prettify any code

### ISSUE THREAD

**Issue by Rundik** [google/code-prettify#571]
So, here is the code
```html
<pre class="prettyprint">
// File: routes/web.php

Route :: get ( '/' , 'WelcomeController@index' );

// File: app/Http/Controllers/WelcomeController.php
namespace app\Http\Controllers ;

 

class WelcomeController
{
public function index ()
{
return 'Hello, World!' ;
}
}
</pre>
```

The code is highlighted but not prettified. I also tried with other languages and got same results

**Comment by johnbalvin** [comment]
show how you are calling pretty print

**Comment by Rundik** [comment]
I don't think I called pretty print. Actually I don't remember, that was a while ago. I think I added the script tag at the end of my page and nothing else

**Comment by johnbalvin** [comment]
Then, you should close your issue
